// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwWF-S6TZ6sYwBMnJNceyUFtvQHozUGE',
    appId: '1:572728946116:web:bed53d9e91c1cd742d0891',
    messagingSenderId: '572728946116',
    projectId: 'c0d3rz-a0ab2',
    authDomain: 'c0d3rz-a0ab2.firebaseapp.com',
    storageBucket: 'c0d3rz-a0ab2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAew8PRu5PrB7rvSIFeY0vwkWJ8_Ar-5iM',
    appId: '1:572728946116:android:7ad9ef288a5d2bd62d0891',
    messagingSenderId: '572728946116',
    projectId: 'c0d3rz-a0ab2',
    storageBucket: 'c0d3rz-a0ab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgqub4WeIqbo8fn9X39QiZTM_8aRcdaM4',
    appId: '1:572728946116:ios:794ab8ec5f46b4692d0891',
    messagingSenderId: '572728946116',
    projectId: 'c0d3rz-a0ab2',
    storageBucket: 'c0d3rz-a0ab2.appspot.com',
    iosBundleId: 'com.example.coders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgqub4WeIqbo8fn9X39QiZTM_8aRcdaM4',
    appId: '1:572728946116:ios:7fdce29abcca18152d0891',
    messagingSenderId: '572728946116',
    projectId: 'c0d3rz-a0ab2',
    storageBucket: 'c0d3rz-a0ab2.appspot.com',
    iosBundleId: 'com.example.coders.RunnerTests',
  );
}
